version: "1.0"
services:
  - name: dark-mods-panel
    type: web
    image: koyeb/pypy:3
    build:
      command: pip install -r requirements.txt
    run:
      command: gunicorn --bind 0.0.0.0:8080 app:app
    ports:
      - port: 8080
        protocol: http
